name: Unit Tests
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: Pytest 
      uses: dariocurr/pytest-summary@v1
