name: Unit Tests
on:
  pull_request:
    branches:
    - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - name: actions-pytest
      uses: xoviat/actions-pytest@0.1-alpha2
      
